#!/bin/sh
# postinst script for ultrabay-scripts
#
# see: dh_installdeb(1)

set -e

COMMONFUNCTIONS=/usr/share/ultrabay-scripts/ultrabay_common

if [ -f $COMMONFUNCTIONS ]
then
    . $COMMONFUNCTIONS
fi

if [ -x "/etc/init.d/ultrabay-scripts" ]
then
    update-rc.d ultrabay-scripts defaults
fi

if which update-icon-caches >/dev/null 2>&1
then
    update-icon-caches /usr/share/icons/battery.png /usr/share/icons/cogwheels.png
fi

case "$1" in
  configure)

    create_battery_rules ()
    {
    ULTRABATTERYRULES=/etc/udev/rules.d/50-ultrabay-battery.rules

    if [ -f ${ULTRABATTERYRULES} ]
    then
        cp -p ${ULTRABATTERYRULES} ${ULTRABATTERYRULES}_previous
    fi

    if [ "$(/bin/ls /sys/devices/platform/dock.? > /dev/null 2>&1; echo $?)" = "0" ] && \
       [ -d "$(dirname $(/bin/grep -l battery_bay /sys/devices/platform/dock.?/type))" ]
    then
        cat > ${ULTRABATTERYRULES} << UBATRULESCREATION
# Generic rule to run ultrabay_battery script whenever power supply
# connector is plugged or unplugged.

SUBSYSTEM=="power_supply", ENV{POWER_SUPPLY_NAME}="AC0", ATTR{online}=="0", RUN+="/usr/sbin/ultrabay_battery"
SUBSYSTEM=="power_supply", ENV{POWER_SUPPLY_NAME}="AC0", ATTR{online}=="1", RUN+="/usr/sbin/ultrabay_battery"
UBATRULESCREATION

	if [ "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/.)" ]; then
	  echo "We are chrooted!"
	else
	  /sbin/udevadm control --reload-rules
	fi
    fi
    }

    add_wmlive_key ()
    {
      if [ "$(apt-key list | grep -c "4096R/22F0F947 2015-12-13" 2>/dev/null)" != "1" ]
      then
        apt-key add - >/dev/null 2>&1 << WMLIVEKEY
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQINBFZt018BEADJQY63rOWTNFHb/UoT61sv714yJWhkPjrEsIIMbOVD2L+Hkb9T
hJz9zkBQimClhaDLWoe8Yz0fWElesg0orz4ugZFmD/SLTown0TwMFWMXZ5r+rmIn
dCX32Iy9t++iP0u5Be2fENrNxJQnoP6WHEOpgrQNAyYLOTCG+aBeeBvdt+urJsVC
rkDbP21D0qkp3MOiUyQJtkiXxeyrQx7QjcD6cMOAP7wRYB64LOd1y+8xCeafqDVw
8ewz/H9s1bSNLSlwkOHBARZ6vzBpJAY6PG8BUIav3jQfpNK+RCaPDzBG5R8vbDh/
mGtmOaQ2hD3gKs0DBw5aUpti6FZQJ5fEmZ+0PBeuLAsgk+9reVl72lIp5fjTgtvh
hPq7GguuuUL5pzgfaUhCopu+cC51sHwZdtYa8WYGHpO4k7Z6gsKHw6U0tPRzxARA
Z4ZwGFDDZTWrDtUKKbmYptZBK3kivFLEHzD8Ft5lE3/SSmsFL9TEhy0tvQ9tpHXH
Xx9zfTPUmo2Mu+Naf9zAH5Fey/Dtp2oCPVaIqCNSZPEUFO6WxaWwNDopSS/9Kba3
4Zq965J2TKnR2pkDJyCd4PWqEFuha2ZV/PFwnDHfz/KchXzX/JscfT+m9dCYT82Y
DcH7bXp9/Ys83iy7Q7sFKjQazVG3JDsfsLwnyp17R+DtBsQPQfiYII8DfQARAQAB
tDtXaW5kb3cgTWFrZXIgTGl2ZSAoUGFja2FnZSByZXBvc2l0b3J5KSA8d21saXZl
QHJ1bWJlcm8ub3JnPokCOAQTAQIAIgUCVm3TXwIbAwYLCQgHAwIGFQgCCQoLBBYC
AwECHgECF4AACgkQaewwWiLw+UeQRxAAh9nSkW0Zfnq3MtZC2BAH4TuLGKLrIdin
SwBzsuuqq3gzlCwZIL34bBZ7gRt1HVxe8ftCcp4ZX4n0aI84qgXYJqss3yLRJgAq
543V3Gc71nvwqEKwKt+FVexPtAm86Zce3BNH9QXh2PqTFGs/hKTbpOrbX8doyC1E
STf5IJayFUoMK5cKg+figLAK/X3IqlrOye8xOJz2wYPQQJcRlW2eS5MLzNeBRYLB
lim6KTp4NUNSHUCDwc+rhF0gaGmgV0uQLKedVX1fS9qvyfNOX6ylbMTP8ecWe0Zs
kUDZx6mLnlNUI5JTUAxZzkYDGKEPJ9sizluH0YsEkbms0dIDoxwuIA51ligXbT4L
FWF5zEMw9suzpzpw3VQFYqLerUKcYHHgBeFnNRY3h3mxii3+dgodtrFfKxyStoyx
h4beyEPV18RJtR5K4XN1RBrlO7xZTpZ5nqOeEcV0Xwzo6AA8ESEPimtPxrzZgKx3
qt1XTkR9B/RzC26MENfqPW8PCIAG5Iun0v0SNuhZ6/DH78ZDfUoFypHTEKDbhqE0
UFmRjSHcl0UoL1xv8ez3UumxzsWO6W/jZw3zigo9+1xTgoKk69nUM7hZSPNcCLQJ
z9iOyG1rUVZzay9Q2e0PUwQSs45JfTnhDLeTYxIiU5kjNANTQ7Y7780c45O0jMej
GCLxcIEwNXO5Ag0EVm3TXwEQALVh/4QQb1zMn1jD99X71qha664blHO7VBKzeEZU
qGO4z6zcAU8z+iSgG0foQlC66yH05vMqT+nzlGTHNIol08ceFPfcybGTeN6y5oM4
pf2dozhickD1wvT4WgFlVeLf2qwGvLeudeS0XYgQ8MoBCMjaGWnM1WufpQsXRbtp
agwBe1haFZ2HsL7Qfl7FIbmctPbawvF5UjMDLbA5MEdc7k3oRLEWTWaucUMdGStG
S0OXwMcccbow0xgUVeFJN6hx+9VKOAS9Dz2Z9gicHQgSrX+vwnoY9HJQCll9iKNn
uoazOhBPIKaqX57/S6er4ki5uXAEZ+QpbAyM4H/N6LmiucFcIROBujRGq1M/u2xT
2QJcYelP3AL0z8caY211SzF1xe8z2/oUHvHtBPcE0UM5lZgrsA3nKgJoQl3VScKK
OU5ZVsersX9MWTvBoLj8TmJx/h0WIEmGziKTbe7ULj1evWWcYMxknYJEalIe0u9o
GUDesz8WDLV9GqnGSTMHGJ5Kt0cEvR4DwDCruxmGNIy3AaegAhHh5+/GTBFgyD0g
d29RFPSIdu8vLE8uEnzxMo7HTb6KYQu1SggDC5Gvg4/2nqNIx7CvqyWTpK3n5ZIe
xQTMVDZITfnrHok+1b/WDxX5kI3EGp8AkQ3lGSF94UY1d1RGcXjwVkiZ0kYpNBNm
w7SHABEBAAGJAh8EGAECAAkFAlZt018CGwwACgkQaewwWiLw+UfZ2hAAgD+0lwjd
RItzmVTiif0cK8xNrc8v+NjPBey6QEmgD7dd3g9R1c/rX4QVKKXhWy7Fq1hu9D9I
6zhIM5+CTSk0F0M41WYOgv4GT3ZSNaGjM57s7lOxIMOaSFJDlvLvUGkRgGpk47Pw
D6QnY1mRCnjRYgwGkXffZcNHhMPDp8NgrMsHI1zGfuUP+17moi/S9zVFU8uWNMHd
437CeoSgMGFvBs0S5fN00nU2HEffShG2+D9z8Ze8h3t5XFCCHuj0nnvbAONFgVrA
ZPFMPWQ+2xOTFditkRY/Gvg78WgQ6bS7xEl4GZSorMDRz+vN+lCz4KqT2dsBKxZu
F6l0zbPXQ2GLerZmGg6DPFXayLS5TV8MxU0vwJWGar0jj83fsgSqA5Sjs0xpoeNj
Sr1dBnD8SWSSvmZMMF7mH7zYC8cOgO84KwLpb5dRxORi4+fYGJ0dg2POcS+DGoDB
TsAJ/buS8aH/RLmLQOuaPzSJXt4g6PN/puL5goWP9/iNJH3UgjJFK3nhzgKqYyih
42xMyjjibUobZk7EzqI4nHZv/yXuUBMPR8wF9+ghkAlt4u1TCpBN5o6KcP3r+au+
CGCzfkCl1cV81LlHu+hAzaUkLN3ucoIfN7fEHWYWAls5NTR3YdCwCSTIT6zLw0Dx
tJIee2pKpsChHEHipH7jAFbh/6MD65kN/rM=
=7VSf
-----END PGP PUBLIC KEY BLOCK-----
WMLIVEKEY
      fi
    }

    add_repo_uri ()
    {
      APTREPOFILE=/etc/apt/sources.list.d/ultrabay-scripts.list 
      cat > ${APTREPOFILE} << REPOURIENTRY
# automatically installed by ultrabay-scripts package
deb http://wmlive.rumbero.org/repo jessie main
REPOURIENTRY
    }

    add_wmlive_key
    add_repo_uri 

    check_if_thinkpad

    if [ "$(/bin/ls /sys/devices/platform/dock.? > /dev/null 2>&1; echo $?)" != "0" ]
    then
        echo "This Thinkpad is not equipped with an UltraBay."
        exit 0
    else
        create_battery_rules
        [ -s /etc/udev/rules.d/50-thinkpad-ultrabay.rules ] && mv -v /etc/udev/rules.d/50-thinkpad-ultrabay.rules /etc/udev/rules.d/50-ultrabay-devices.rules
        [ -x /usr/sbin/ultrabay_insert ] && [ ! -s /etc/udev/rules.d/50-ultrabay-devices.rules ] && /usr/sbin/ultrabay_insert -mkrules
    fi

    exit 0
 ;;
esac

exit 0
