#!/bin/sh
# postinst script for ultrabay-scripts
#
# see: dh_installdeb(1)

set -e

COMMONFUNCTIONS=/usr/share/ultrabay-scripts/ultrabay_common

if [ -f $COMMONFUNCTIONS ]
then
    . $COMMONFUNCTIONS
fi

if [ -x "/etc/init.d/ultrabay-scripts" ]
then
    update-rc.d ultrabay-scripts defaults
fi

if which update-icon-caches >/dev/null 2>&1
then
    update-icon-caches /usr/share/icons/battery.png /usr/share/icons/cogwheels.png
fi

case "$1" in
  configure)

    create_battery_rules ()
    {
    ULTRABATTERYRULES=/etc/udev/rules.d/50-ultrabay-battery.rules

    if [ -f ${ULTRABATTERYRULES} ]
    then
        cp -p ${ULTRABATTERYRULES} ${ULTRABATTERYRULES}_previous
    fi

    if [ "$(/bin/ls /sys/devices/platform/dock.? > /dev/null 2>&1; echo $?)" = "0" ] && \
       [ -d "$(dirname $(/bin/grep -l battery_bay /sys/devices/platform/dock.?/type))" ]
    then
        cat > ${ULTRABATTERYRULES} << UBATRULESCREATION
# Generic rule to run ultrabay_battery script whenever power supply
# connector is plugged or unplugged.

SUBSYSTEM=="power_supply", ENV{POWER_SUPPLY_NAME}="AC0", ATTR{online}=="0", RUN+="/usr/sbin/ultrabay_battery"
SUBSYSTEM=="power_supply", ENV{POWER_SUPPLY_NAME}="AC0", ATTR{online}=="1", RUN+="/usr/sbin/ultrabay_battery"
UBATRULESCREATION

        if [ "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/.)" ]
        then
            echo "We are chrooted!"
        else
            /sbin/udevadm control --reload-rules
        fi
    fi
    }

    check_if_thinkpad

    if [ "$(/bin/ls /sys/devices/platform/dock.? > /dev/null 2>&1; echo $?)" != "0" ]
    then
        echo "This Thinkpad is not equipped with an UltraBay."
        exit 0
    else
        create_battery_rules
        [ -s /etc/udev/rules.d/50-thinkpad-ultrabay.rules ] && mv -v /etc/udev/rules.d/50-thinkpad-ultrabay.rules /etc/udev/rules.d/50-ultrabay-devices.rules
        [ -x /usr/sbin/ultrabay_insert ] && [ ! -s /etc/udev/rules.d/50-ultrabay-devices.rules ] && /usr/sbin/ultrabay_insert -mkrules
    fi

    exit 0
 ;;
esac

exit 0
