#!/bin/sh
#set -x

# Copyright (C) 2011 by Window Maker Live <wmlive@rumbero.org>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Primary source of inspiration and original code:
# http://www.thinkwiki.org/wiki/How_to_hotswap_Ultrabay_devices#Script_for_Ultrabay_eject
# http://www.thinkwiki.org/wiki/Talk:How_to_hotswap_Ultrabay_devices

SCRIPTNAME="$(basename $0)"

COMMONFUNCTIONS=/usr/share/ultrabay-scripts/ultrabay_common

if [ -f $COMMONFUNCTIONS ]
then
    . $COMMONFUNCTIONS
else
    echo File $COMMONFUNCTIONS not found, cannot proceed
    exit 1
fi

check_if_thinkpad

thinkpad_smapi_check #|| thinkpad_tpacpi_bat_check

ultrabay_notify_config

ultrabay_battery_interface

if [ "$(cat $BATDEV/docked)" = "1" ] && [ -e $SMAPIDIR/BAT1 ]
then
    if [ "$(cat $SMAPIDIR/ac_connected)" = "0" ] && [ "$(cat $SMAPIDIR/BAT1/installed)" = "1" ]
    then
        if [ "$(cat $SMAPIDIR/BAT0/installed)" = "1" ] && [ "$(cat $SMAPIDIR/BAT0/remaining_percent)" -gt "5" ]
        then
            echo 1 > $SMAPIDIR/BAT0/force_discharge
            logger "$SCRIPTNAME": Ultrabay and main battery present, switching battery discharge order
            echo "$SCRIPTNAME: Ultrabay and main battery present, switching battery discharge order"
            [ -x "$DESKTOPNOTIFY" ] && $DESKTOPNOTIFYCMD -u normal -t 10000 "Ultrabay and main battery present:" "Switching battery discharge order"
        elif [ "$(cat $SMAPIDIR/BAT0/installed)" = "0" ] || [ "$(cat $SMAPIDIR/BAT0/remaining_percent)" -lt "5" ]
        then
            echo 0 > $SMAPIDIR/BAT0/force_discharge
            logger "$SCRIPTNAME": Main battery either empty or absent, running from Ultrabay battery now.
            echo "$SCRIPTNAME: Main battery either empty or absent, running from Ultrabay battery now."
            [ -x "$DESKTOPNOTIFY" ] && $DESKTOPNOTIFYCMD -u normal -t 10000 "Main battery either empty or absent:" "Running from Ultrabay battery now."
        fi
    elif [ "$(cat $SMAPIDIR/ac_connected)" = "1" ] && [ "$(cat $SMAPIDIR/BAT0/force_discharge)" = "1" ]
    then
        echo 0 > $SMAPIDIR/BAT0/force_discharge
        echo "$SCRIPTNAME: AC adapter is connected, disabling main battery discharge"
        [ -x "$DESKTOPNOTIFY" ] && $DESKTOPNOTIFYCMD -u normal -t 10000 "AC adapter is connected:" "Disabling main battery discharge"
    fi
elif [ "$(cat $BATDEV/docked)" = "0" ] && [ -e $SMAPIDIR/BAT1 ]
then
    if [ "$(cat $SMAPIDIR/BAT0/installed)" = "1" ] && [ "$(cat $SMAPIDIR/BAT0/force_discharge)" = "1" ]
    then
        [ "$(cat $SMAPIDIR/BAT1/installed)" = "0" ] && echo 0 > $SMAPIDIR/BAT0/force_discharge
    fi
    echo "No UltraBay battery inserted:"
    echo "Disabled forced battery discharge"
    [ -x "$DESKTOPNOTIFY" ] && $DESKTOPNOTIFYCMD -u normal -t 10000 "No UltraBay battery inserted:" "Disabled forced battery discharge"
fi
